@startuml ecommerce_class_diagram
left to right direction
abstract class UnitBase {
  #int id
  #float hp
  #float attack
  #float masicAttack
  #float defense
  #float speed
  #Piece[] pieces 
  +void Move()
  +void Attack()
  +void Damage()
}

class Unit {
}

abstract class PieceBase {
  #int id
}

class Piece {
}

class main {
}

class GameManager {
}

class BattleManager {
}

class TurnManager {
}

class Parameter {
}

UnitBase <|-- Unit
PieceBase <|-- Piece

main *-- Game
@enduml